HTML:
- any: ['**/*.html']
EJS:
- any: ['**/*.ejs']
CSS:
- any: ['**/*.css']
JavaScript:
- any: ['**/*.js']
  all: ['!functions/index.js']
images:
- any: ['**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.svg', '**/*.gif']
workflows:
- any: ['.github/workflows/**/*']
front-end:
- any: ['public/**/*']
back-end:
- any: ['functions/**/*']
dependencies:
- any: ['functions/package.json', 'functions/package-lock.json']
documentation:
- any: ['**/*.md']
